[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/payment-success.html"
  to   = "/STEP_Free_Preview.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
